{
 "title": "New dashboard",
 "time": { "from": "2023-06-08T12:20:44.716Z", "to": "2023-06-08T14:23:19.060Z" },
 "panels": [
  {
   "title": "Total CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{namespace=\"monitoring\"}[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"user\"}[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Rate for 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"user\"}[1m]) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU Usage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"system\"}[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod and Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(pod_name, container) (container_memory_usage_bytes{namespace=\"monitoring\", pod=~\"ecc-demo-service-79d7589f4c-5hx2h|ecc-demo-service-79d7589f4c-j6gvc|ecc-demo-service-79d7589f4c-4cblr\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{namespace=\"monitoring\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}